### ISSUE TITLE
Missing files and classes

### ISSUE THREAD

**Issue by Seanba** [mcraiha/CSharp-zstd#1]
Hi there. The project appears to missing a `Strategy` enum as well as `DataBlock` and `FseCompressionTable` class definitions. As such the code does not compile.

**Comment by mcraiha** [comment]
Yes, you are right. And I am sorry about that (this project has been on the back burner). I will fix this later today. I already added a Action to check that the test cases run correctly so hopefully I can avoid issues in future.

**Comment by mcraiha** [comment]
Should compile now.
